'use strict';
/* Fully offline portfolio concept. No APIs, tracking, payments or contact submission. */
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const zones = [
  {id:'neck',name:'Шия',x:50,y:22}, {id:'shoulders',name:'Плечі',x:66,y:30},
  {id:'back',name:'Спина',x:50,y:39}, {id:'lower',name:'Поперек',x:50,y:50},
  {id:'legs',name:'Ноги',x:62,y:74}, {id:'whole',name:'Усе тіло',x:37,y:59}
];
const rituals = {
  relax:{name:'М' + "'" + 'яке розслаблення',short:'Розслаблення',price:900,icon:'◌',text:'Повільний темп, м’який дотик і відчуття спокою.',pressure:'М’яка'},
  deep:{name:'Глибоке опрацювання',short:'Глибока робота',price:1100,icon:'✧',text:'Уважна робота з обраною зоною у комфортному темпі.',pressure:'Середня'},
  recovery:{name:'Відновлення після активності',short:'Відновлення',price:1200,icon:'☼',text:'Турбота про тіло після насиченого дня чи спорту.',pressure:'Середня'}
};
const therapists = [
  {id:'anastasia',name:'Анастасія',initial:'А',for:'relax',approach:'Делікатний дотик і повільний темп. Простір, де легко видихнути.',tags:['Розслаблення','М’який підхід']},
  {id:'alexander',name:'Олександр',initial:'О',for:'deep',approach:'Послідовна, уважна робота зі спиною та плечовим поясом.',tags:['Глибока робота','Спина та плечі']},
  {id:'maria',name:'Марія',initial:'М',for:'recovery',approach:'Увага до відчуттів тіла після навантаження та активного дня.',tags:['Відновлення','Індивідуальний темп']}
];
const times = ['10:00','11:30','13:00','14:30','16:00','17:30','19:00','20:30'];
const storageKey='massage-portfolio-demo-v1';
let state,step=0,lastBooking=null,previousFocus=null,breathTimer,previewStep=0,toastTimer;
const bookingDialog=$('#booking-dialog');
function freshState(){return {zone:'whole',ritual:'relax',duration:60,pressure:'М’яка',therapist:'anastasia',date:dateKey(new Date()),time:'',waitlist:false};}
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function parseDate(value){return new Date(`${value}T12:00:00`);}
function dateLabel(value){return parseDate(value).toLocaleDateString('uk-UA',{day:'numeric',month:'long'});}
function price(s=state){return rituals[s.ritual].price+({30:-300,60:0,90:400}[s.duration]||0);}
function money(value){return value.toLocaleString('uk-UA')+' ₴';}
function zoneName(id){return zones.find(z=>z.id===id)?.name||'Усе тіло';}
function specialist(s=state){return therapists.find(t=>t.id===s.therapist)||therapists[0];}
function escapeHTML(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function showToast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function bodyMarkup(prefix){return `<svg viewBox="0 0 260 440" aria-hidden="true"><defs><linearGradient id="${prefix}-fill" x1="0" x2="1"><stop stop-color="#332619"/><stop offset=".35" stop-color="#a78a6355"/><stop offset=".52" stop-color="#68513833"/><stop offset=".7" stop-color="#a78a6355"/><stop offset="1" stop-color="#332619"/></linearGradient></defs><g style="--body-fill:url(#${prefix}-fill)"><path class="body-shape" style="fill:url(#${prefix}-fill)" d="M130 18C108 18 102 33 103 49C102 64 111 78 117 81L117 96C110 102 94 103 84 109C72 118 70 139 68 161L60 213L53 254C51 265 54 274 59 275L63 258L66 273L71 260L78 215L88 176L92 148L96 176L100 204L94 234C88 253 92 271 98 289L101 332L105 375L101 408C98 422 105 424 121 420L124 402L124 359L128 311L130 281L132 311L136 359L136 402L139 420C155 424 162 422 159 408L155 375L159 332L162 289C168 271 172 253 166 234L160 204L164 176L168 148L172 176L182 215L189 260L194 273L197 258L201 275C206 274 209 265 207 254L200 213L192 161C190 139 188 118 176 109C166 103 150 102 143 96L143 81C149 78 158 64 157 49C158 33 152 18 130 18Z"/><g class="body-muscle"><path d="M130 83V244M116 98L100 127L124 148L130 132L136 148L160 127L144 98M99 129C102 151 112 168 127 173M161 129C158 151 148 168 133 173M100 172L119 198L130 218L141 198L160 172M98 221L117 234L130 248L143 234L162 221M94 248Q111 236 128 264M166 248Q149 236 132 264M101 285L116 277L113 329L106 349M159 285L144 277L147 329L154 349M109 354L118 365L113 399M151 354L142 365L147 399M83 122L79 168L69 219M177 122L181 168L191 219M117 30Q130 44 143 30M106 53Q130 67 154 53M116 66L130 76L144 66"/><path d="M119 114L130 122L141 114M119 152L130 158L141 152M119 177L130 183L141 177M119 197L130 203L141 197M120 218L130 224L140 218"/></g></g></svg>${zones.filter(z=>z.id!=='whole').map(z=>`<button class="body-point" data-zone="${z.id}" aria-label="Обрати зону: ${z.name}" style="left:${z.x}%;top:${z.y}%"><span>${z.name}</span></button>`).join('')}`;}
function zoneButtons(){return zones.map(z=>`<button class="zone-chip ${state&&state.zone===z.id?'selected':''}" data-zone="${z.id}" aria-pressed="${Boolean(state&&state.zone===z.id)}">${z.name}</button>`).join('');}
function openDialog(el){previousFocus=document.activeElement;$$('dialog[open]').forEach(d=>d.close());el.showModal();document.body.classList.add('locked');}
function closeDialog(el){el.close();}
$$('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')){document.body.classList.remove('locked');previousFocus?.focus?.();}if(dialog.id==='breath-dialog')clearInterval(breathTimer);});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog);});});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));
function openBooking(options={}){state={...freshState(),...options};if(options.ritual&&!options.therapist){state.therapist=therapists.find(t=>t.for===state.ritual).id;state.pressure=rituals[state.ritual].pressure;}step=0;renderBooking();openDialog(bookingDialog);}
$$('[data-book]').forEach(b=>b.addEventListener('click',()=>openBooking()));
$$('[data-ritual]').forEach(b=>b.addEventListener('click',()=>openBooking({ritual:b.dataset.ritual})));
$('#home-body').innerHTML=bodyMarkup('home');$('#home-zones').innerHTML=zoneButtons();
$$('#home-body [data-zone],#home-zones [data-zone]').forEach(b=>b.addEventListener('click',()=>openBooking({zone:b.dataset.zone})));
$('#therapist-grid').innerHTML=therapists.map(t=>`<article class="therapist-card"><div class="profile-mark" aria-hidden="true">${t.initial}</div><h3>${t.name}</h3><p>${t.approach}</p><div class="tag-row">${t.tags.map(tag=>`<span class="tag">${tag}</span>`).join('')}</div><button class="text-link" data-master="${t.id}">Обрати майстра <span>↗</span></button></article>`).join('');
$$('[data-master]').forEach(b=>b.addEventListener('click',()=>{const t=therapists.find(t=>t.id===b.dataset.master);openBooking({therapist:t.id,ritual:t.for,pressure:rituals[t.for].pressure});}));
function heading(title,subtitle=''){return `<div class="step-heading"><div><h2 id="booking-title" tabindex="-1">${title}</h2>${subtitle?`<p class="step-description">${subtitle}</p>`:''}</div><span class="step-number">КРОК ${step+1} / 6</span></div>`;}
function footer(next='Далі →',enabled=true){return `<div class="step-footer"><button class="outline" data-action="back">${step===0?'Закрити':'← Назад'}</button><span class="muted">${step>0?`${state.duration} хв · ${money(price())}`:'Ваш темп. Ваш вибір.'}</span><button class="primary" data-action="next" ${enabled?'':'disabled'}>${next}</button></div>`;}
function isUnavailable(time,index,date){return (index+parseDate(date).getDate())%5===0;}
function renderBooking(){let html='';$('#progress-fill').style.width=`${Math.min(100,(step+1)/6*100)}%`;
  if(step===0){html=heading('Що відчуває<br><em>ваше тіло сьогодні?</em>','Оберіть зону, якій хочеться приділити увагу.')+`<div class="step-layout"><div class="booking-body"><div class="body-diagram">${bodyMarkup('modal')}</div></div><div class="booking-zone-area"><span class="form-label">Почнімо з вашого фокуса</span><div class="zone-list">${zoneButtons()}</div><div class="demo-notice">✧ Це підбір за вподобаннями. Якщо є біль, травма чи інші обмеження, уточніть можливість масажу у спеціаліста.</div></div></div>`+footer();}
  if(step===1){html=heading('Чого вам<br><em>хочеться зараз?</em>','Задайте настрій, тривалість та інтенсивність сеансу.')+`<div class="choice-grid">${Object.entries(rituals).map(([id,r])=>`<button class="choice-card ${state.ritual===id?'selected':''}" data-choice="${id}" aria-pressed="${state.ritual===id}"><span class="choice-icon">${r.icon}</span><strong>${r.short}</strong><small>${r.text}</small></button>`).join('')}</div><span class="form-label">Ваш час</span><div class="option-row">${[30,60,90].map(d=>`<button class="option ${state.duration===d?'selected':''}" data-duration="${d}" aria-pressed="${state.duration===d}">${d} хвилин</button>`).join('')}</div><span class="form-label">Бажана інтенсивність</span><div class="option-row">${['М’яка','Середня','Інтенсивна'].map(p=>`<button class="option ${state.pressure===p?'selected':''}" data-pressure="${p}" aria-pressed="${state.pressure===p}">${p}</button>`).join('')}</div><div class="mini-preview"><span>${zoneName(state.zone)} · ${state.duration} хв</span><span>${money(price())}</span></div>`+footer('Обрати майстра →');}
  if(step===2){html=heading('Той, хто відчує<br><em>ваш ритм.</em>','Вигадані профілі для демонстрації. Підказка враховує обраний стиль сеансу.')+`<div class="booking-therapists">${therapists.map(t=>`<button class="select-therapist ${state.therapist===t.id?'selected':''}" data-therapist="${t.id}" aria-pressed="${state.therapist===t.id}"><span class="recommended">${state.ritual===t.for?'ПІДХОДИТЬ ЗА СТИЛЕМ':'ІНШИЙ ПІДХІД'}</span><span class="selection-indicator">${state.therapist===t.id?'✓':'○'}</span><span class="profile-mark">${t.initial}</span><strong>${t.name}</strong><small>${t.approach}</small><small>${t.tags.join(' · ')}</small></button>`).join('')}</div>`+footer('Обрати час →');}
  if(step===3){const dates=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()+i);return {key:dateKey(d),label:i===0?'Сьогодні':i===1?'Завтра':d.toLocaleDateString('uk-UA',{weekday:'short'}),num:d.toLocaleDateString('uk-UA',{day:'numeric',month:'short'})};});html=heading('Знайдіть час<br><em>для себе.</em>','Приклад розкладу — ці слоти не пов’язані з реальною студією.')+`<div class="mini-preview"><span>${specialist().name} · ${rituals[state.ritual].short}</span><span>${state.duration} хв</span></div><div class="date-grid">${dates.map(d=>`<button class="date-option ${state.date===d.key?'selected':''}" data-date="${d.key}" aria-pressed="${state.date===d.key}">${d.label}<span>${d.num}</span></button>`).join('')}</div><span class="form-label">Демонстраційні слоти</span><div class="time-grid">${times.map((t,i)=>`<button class="time-option ${state.time===t?'selected':''} ${isUnavailable(t,i,state.date)?'unavailable':''}" data-time="${t}" aria-pressed="${state.time===t}" ${isUnavailable(t,i,state.date)?'disabled aria-label="'+t+' — зайнято у деморозкладі"':''}>${t}</button>`).join('')}</div><button class="waitlist inline-button" data-action="waitlist">${state.waitlist?'✓ Демоочікування додано — сповіщення не надсилаються':'Немає зручного часу? Переглянути демолист очікування'}</button>`+footer('Переглянути ритуал →',Boolean(state.time));}
  if(step===4){html=heading('Ваш персональний<br><em>ритуал готовий.</em>','Перевірте деталі. Будь-який параметр можна змінити.')+`<div class="booking-summary"><img class="summary-image" src="assets/hero.png" alt="Спокійний ритуал турботи"><div><h3 class="summary-title">${rituals[state.ritual].name}</h3><div class="summary-line"><span>Фокус</span><span>${zoneName(state.zone)}</span></div><div class="summary-line"><span>Тривалість · інтенсивність</span><span>${state.duration} хв · ${state.pressure.toLowerCase()}</span></div><div class="summary-line"><span>Майстер</span><span>${specialist().name}</span></div><div class="summary-line"><span>Дата та час</span><span>${dateLabel(state.date)} · ${state.time}</span></div><div class="summary-line total"><span>Приклад вартості</span><span>${money(price())}</span></div></div></div><div class="demo-notice">ДЕМО · Натискання нижче лише покаже екран підтвердження. Заявка не надсилається, кошти не списуються, реальної броні не буде.</div>`+footer('Підтвердити демозапис →');}
  if(step===5){html=`<div class="confirmation"><span class="check-circle">✓</span><p class="eyebrow">ВАШ МОМЕНТ ТИШІ</p><h2 id="booking-title" tabindex="-1">Демосеанс<br><em>створено.</em></h2><p class="confirmed-time">${dateLabel(state.date)}, ${state.time}</p><p class="muted">${rituals[state.ritual].name} · ${state.duration} хв<br>${zoneName(state.zone)} · ${specialist().name}</p><div class="confirmation-actions"><button class="outline" data-action="calendar">↓ Додати демоподію</button><button class="outline" data-action="reschedule">↻ Змінити час</button><button class="outline" data-action="cancel">× Скасувати демосеанс</button></div><div class="demo-notice">Це приклад підтвердження для портфоліо. Сеанс збережено лише в цьому браузері, якщо доступне локальне сховище. Ніхто не отримав заявку.</div><button class="primary" style="margin-top:25px" data-action="close">Повернутися до спокою ↗</button></div>`;}
  $('#booking-content').innerHTML=`<div class="booking-content-inner">${html}</div>`;
  $$('[data-zone]',bookingDialog).forEach(b=>{if(b.dataset.zone===state.zone)b.classList.add('selected');b.addEventListener('click',()=>{state.zone=b.dataset.zone;renderBooking();focusChoice('data-zone',state.zone);});});
  $$('[data-choice]',bookingDialog).forEach(b=>b.addEventListener('click',()=>{state.ritual=b.dataset.choice;state.pressure=rituals[state.ritual].pressure;state.therapist=therapists.find(t=>t.for===state.ritual).id;renderBooking();focusChoice('data-choice',state.ritual);}));
  for(const [attr,key,convert] of [['duration','duration',Number],['pressure','pressure',String],['therapist','therapist',String],['date','date',String],['time','time',String]]){$$(`[data-${attr}]`,bookingDialog).forEach(b=>b.addEventListener('click',()=>{state[key]=convert(b.dataset[attr]);if(key==='date')state.time='';renderBooking();focusChoice('data-'+attr,state[key]);}));}
  $$('[data-action]',bookingDialog).forEach(b=>b.addEventListener('click',()=>bookingAction(b.dataset.action)));
}
function focusChoice(attr,value){$$(`[${attr}]`,bookingDialog).find(b=>b.getAttribute(attr)===String(value))?.focus({preventScroll:true});}
function focusStep(){bookingDialog.scrollTop=0;$('#booking-title')?.focus({preventScroll:true});}
function bookingAction(action){
  if(action==='back'){if(step===0){closeDialog(bookingDialog);return;}step--;}
  if(action==='next'){if(step===3&&!state.time)return;if(step===4){lastBooking={...state};saveBooking();}step=Math.min(5,step+1);}
  if(action==='close'){closeDialog(bookingDialog);return;}
  if(action==='calendar'){downloadCalendar();return;}
  if(action==='reschedule'){step=3;state.time='';}
  if(action==='cancel'){lastBooking=null;try{localStorage.removeItem(storageKey);}catch{}$('#last-booking').hidden=true;closeDialog(bookingDialog);showToast('Демосеанс скасовано.');return;}
  if(action==='waitlist'){state.waitlist=true;renderBooking();showToast('Демо: додано до очікування. Контакти не збираються.');return;}
  renderBooking();focusStep();
}
function saveBooking(){try{localStorage.setItem(storageKey,JSON.stringify(lastBooking));}catch{}$('#last-booking').hidden=false;}
function validStored(s){return s&&zones.some(z=>z.id===s.zone)&&Object.keys(rituals).includes(s.ritual)&&[30,60,90].includes(s.duration)&&therapists.some(t=>t.id===s.therapist)&&['М’яка','Середня','Інтенсивна'].includes(s.pressure)&&/^\d{4}-\d{2}-\d{2}$/.test(s.date)&&!Number.isNaN(parseDate(s.date).valueOf())&&times.includes(s.time);}
try{const stored=JSON.parse(localStorage.getItem(storageKey));if(validStored(stored)){lastBooking=stored;$('#last-booking').hidden=false;}}catch{}
$('#last-booking').addEventListener('click',()=>{if(!lastBooking)return;state={...lastBooking};step=5;renderBooking();openDialog(bookingDialog);});
function downloadFile(content,mime,name){const blob=new Blob([content],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function downloadCalendar(){const start=new Date(`${state.date}T${state.time}:00`);const end=new Date(start.getTime()+state.duration*60000);const stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Massage Portfolio//Demo//UK','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:demo-${Date.now()}@portfolio.invalid`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,'SUMMARY:ДЕМО — ритуал турботи','DESCRIPTION:Подія з портфоліо. Реального запису не існує.','STATUS:TENTATIVE','END:VEVENT','END:VCALENDAR'].join('\r\n')+'\r\n';downloadFile(content,'text/calendar;charset=utf-8','demo-session.ics');showToast('Завантажено демоподію для календаря.');}
// Four-scene atmosphere preview; intentionally does not pretend to be a video.
const scenes=[{title:'Прибуття.<br><em>Видихніть.</em>',text:'Залиште справи за дверима. Кілька хвилин, щоб сповільнитися і відчути простір.',position:'25% center',scale:1.04},{title:'Налаштування.<br><em>У вашому темпі.</em>',text:'Поговоріть про побажання. Оберіть комфортний дотик, світло та тишу.',position:'65% center',scale:1.16},{title:'Ваш сеанс.<br><em>Тільки тут і зараз.</em>',text:'М’яке світло, натуральні текстури й увага до відчуттів. Дозвольте цьому часу належати вам.',position:'75% center',scale:1.08},{title:'Чай і тиша.<br><em>Без поспіху.</em>',text:'Кілька хвилин перед поверненням у свій день. Збережіть це відчуття спокою.',position:'10% center',scale:1.24}];
function renderPreview(){const s=scenes[previewStep];$('#experience-count').textContent=`0${previewStep+1} / 04 — ПЕРЕГЛЯД АТМОСФЕРИ`;$('#experience-title').innerHTML=s.title;$('#experience-text').textContent=s.text;$('#experience-dialog>img').style.objectPosition=s.position;$('#experience-dialog>img').style.transform=`scale(${s.scale})`;$('#preview-prev').disabled=previewStep===0;$('#preview-next').textContent=previewStep===3?'Мій ритуал ↗':'Далі →';$('#preview-dots').innerHTML=scenes.map((_,i)=>`<button class="${previewStep===i?'active':''}" aria-label="Етап ${i+1}" aria-pressed="${previewStep===i}" data-scene="${i}"></button>`).join('');$$('[data-scene]').forEach(b=>b.addEventListener('click',()=>{previewStep=Number(b.dataset.scene);renderPreview();}));}
function openPreview(){previewStep=0;renderPreview();openDialog($('#experience-dialog'));}
$('#hero-preview').addEventListener('click',openPreview);$('#experience-open').addEventListener('click',openPreview);$('#preview-prev').addEventListener('click',()=>{previewStep=Math.max(0,previewStep-1);renderPreview();});$('#preview-next').addEventListener('click',()=>{if(previewStep===3){openBooking();return;}previewStep++;renderPreview();});
$('#breathe-open').addEventListener('click',()=>{openDialog($('#breath-dialog'));let elapsed=0;$('#breath-title').textContent='Вдих';clearInterval(breathTimer);breathTimer=setInterval(()=>{elapsed=(elapsed+1)%10;$('#breath-title').textContent=elapsed<4?'Вдих':'Видих';},1000);});
$('#gift-open').addEventListener('click',()=>openDialog($('#gift-dialog')));
$('#gift-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#gift-name').value.trim()||'Для когось особливого';const message=$('#gift-message').value.trim()||'Нехай цей час буде тільки твоїм.';const words=message.split(/\s+/);const lines=[''];words.forEach(word=>{if((lines[lines.length-1]+' '+word).trim().length>43)lines.push(word);else lines[lines.length-1]+=(lines[lines.length-1]?' ':'')+word;});const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><defs><radialGradient id="g"><stop stop-color="#4b3522"/><stop offset="1" stop-color="#17120e"/></radialGradient></defs><rect width="1200" height="800" fill="url(#g)"/><rect x="30" y="30" width="1140" height="740" rx="8" fill="none" stroke="#b89767"/><rect x="44" y="44" width="1112" height="712" rx="4" fill="none" stroke="#b89767" opacity=".2"/><g text-anchor="middle"><text x="600" y="133" font-family="Arial" font-size="15" letter-spacing="6" fill="#c5a26d">ЧАС ДЛЯ СЕБЕ</text><text x="600" y="254" font-family="Georgia" font-size="48" fill="#f1e3ce">${escapeHTML(name)}</text><text x="600" y="377" font-family="Georgia" font-style="italic" font-size="77" fill="#d4b482">60 хвилин тиші.</text>${lines.slice(0,4).map((l,i)=>`<text x="600" y="${478+i*35}" font-family="Arial" font-size="22" fill="#dacbb7">${escapeHTML(l)}</text>`).join('')}<text x="600" y="673" font-family="Arial" font-size="13" letter-spacing="2" fill="#bfa582">ПЕРСОНАЛЬНЕ ПОБАЖАННЯ · PORTFOLIO DEMO</text><text x="600" y="705" font-family="Arial" font-size="12" fill="#a28f77">Декоративна картка. Не є платіжним сертифікатом.</text></g></svg>`;downloadFile(svg,'image/svg+xml;charset=utf-8','gift-demo.svg');showToast('Персональну демокартку завантажено.');});
$('#menu-toggle').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));$('#menu-toggle').setAttribute('aria-label',open?'Закрити меню':'Відкрити меню');});
$$('#navigation a').forEach(a=>a.addEventListener('click',()=>{$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');$('#menu-toggle').setAttribute('aria-label','Відкрити меню');}));
$('#year').textContent=new Date().getFullYear();
window.addEventListener('scroll',()=>$('#booking-dock').classList.toggle('visible',window.scrollY>550),{passive:true});
if('IntersectionObserver' in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}});},{threshold:.07});$$('.reveal').forEach(el=>{el.classList.add('js-reveal');observer.observe(el);});}
